django2use/works/timepiece/urls.py
from django.conf.urls import include, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView


urlpatterns = [
    # Redirect the base URL to the dashboard.
    url(r'^$', RedirectView.as_view(url=reverse_lazy('dashboard'), permanent=False)),

    url('', include('timepiece.crm.urls')),
    url('', include('timepiece.contracts.urls')),
    url('', include('timepiece.entries.urls')),
    url('', include('timepiece.reports.urls')),
]

django2use/works/timepiece/entries/models.py
from collections import OrderedDict
from decimal import Decimal

from dateutil.relativedelta import relativedelta

from django.contrib.auth.models import User
from django.core import validators
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import F, Q, Sum, Max, Min
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

from timepiece import utils
from timepiece.crm.models import Project


@python_2_unicode_compatible
class Activity(models.Model):
    """
    Represents different types of activity: debugging, developing,
    brainstorming, QA, etc...
    """
    code = models.CharField(
        max_length=5, unique=True,
        help_text='Enter a short code to describe the type of activity that took place.')
    name = models.CharField(
        max_length=50,
        help_text='Now enter a more meaningful name for the activity.')
    billable = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'timepiece_activity'  # Using legacy table name
        ordering = ('name',)
        verbose_name_plural = 'activities'


@python_2_unicode_compatible
class ActivityGroup(models.Model):
    """Activities that are allowed for a project"""
    name = models.CharField(max_length=255, unique=True)
    activities = models.ManyToManyField(Activity, related_name='activity_group')

    class Meta:
        db_table = 'timepiece_activitygroup'  # Using legacy table

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Location(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.CharField(max_length=255, unique=True)

    class Meta:
        db_table = 'timepiece_location'  # Using legacy table name

    def __str__(self):
        return self.name


class EntryQuerySet(models.query.QuerySet):
    """QuerySet extension to provide filtering by billable status"""

    def date_trunc(self, key='month', extra_values=None):
        select = {
            "day": {"date": """DATE_TRUNC('day', end_time)"""},
            "week": {"date": """DATE_TRUNC('week', end_time)"""},
            "month": {"date": """DATE_TRUNC('month', end_time)"""},
            "year": {"date": """DATE_TRUNC('year', end_time)"""},
        }
        basic_values = (
            'user', 'date', 'user__first_name', 'user__last_name', 'billable',
        )
        extra_values = extra_values or ()
        qs = self.extra(select=select[key])
        qs = qs.values(*basic_values + extra_values)
        qs = qs.annotate(hours=Sum('hours')).order_by(
            'user__last_name',
            'user__first_name',
            'user__pk',
            'date')
        return qs

    def timespan(self, from_date, to_date=None, span=None, current=False):
        """
        Takes a beginning date a filters entries. An optional to_date can be
        specified, or a span, which is one of ('month', 'week', 'day').
        N.B. - If given a to_date, it does not include that date, only before.
        """
        if span and not to_date:
            diff = None
            if span == 'month':
                diff = relativedelta(months=1)
            elif span == 'week':
                diff = relativedelta(days=7)
            elif span == 'day':
                diff = relativedelta(days=1)
            if diff is not None:
                to_date = from_date + diff
        datesQ = Q(end_time__gte=from_date)
        datesQ &= Q(end_time__lt=to_date) if to_date else Q()
        datesQ |= Q(end_time__isnull=True) if current else Q()
        return self.filter(datesQ)


class EntryManager(models.Manager):

    def get_queryset(self):
        qs = EntryQuerySet(self.model)
        qs = qs.select_related('activity', 'project__type')

        # ensure our select_related are added.  Without this line later calls
        # to select_related will void ours (not sure why - probably a bug
        # in Django)
        # in other words: do not remove!
        str(qs.query)

        import django
        if django.VERSION >= (1, 8):
            # extra() is slowly but surely being deprecated.
            # Newer Django versions have powerful F expressions to replace it.
            # An entry is billable if both its project and activity are billable.
            # We make use of a Django internal function to force the
            # query to use the logical rather than bitwise conjunction operator.
            project_billable = F('project__type__billable')
            activity_billable = F('activity__billable')
            logical_and = 'AND'  # bitwise would be '&'
            billable = project_billable._combine(activity_billable, logical_and, False)
            qs = qs.annotate(billable=billable)
        else:
            qs = qs.extra({
                'billable': 'timepiece_activity.billable AND '
                            'timepiece_attribute.billable',
            })
        return qs

    def date_trunc(self, key='month', extra_values=()):
        return self.get_queryset().date_trunc(key, extra_values)

    def timespan(self, from_date, to_date=None, span='month'):
        return self.get_queryset().timespan(from_date, to_date, span)


class EntryWorkedManager(models.Manager):

    def get_queryset(self):
        qs = EntryQuerySet(self.model)
        projects = utils.get_setting('TIMEPIECE_PAID_LEAVE_PROJECTS')
        return qs.exclude(project__in=projects.values())


@python_2_unicode_compatible
class Entry(models.Model):
    """
    This class is where all of the time logs are taken care of
    """
    UNVERIFIED = 'unverified'
    VERIFIED = 'verified'
    APPROVED = 'approved'
    INVOICED = 'invoiced'
    NOT_INVOICED = 'not-invoiced'
    STATUSES = OrderedDict((
        (UNVERIFIED, 'Unverified'),
        (VERIFIED, 'Verified'),
        (APPROVED, 'Approved'),
        (INVOICED, 'Invoiced'),
        (NOT_INVOICED, 'Not Invoiced'),
    ))

    user = models.ForeignKey(User, related_name='timepiece_entries')
    project = models.ForeignKey('crm.Project', related_name='entries')
    activity = models.ForeignKey(Activity, related_name='entries')
    location = models.ForeignKey(Location, related_name='entries')
    entry_group = models.ForeignKey(
        'contracts.EntryGroup', blank=True, null=True, related_name='entries',
        on_delete=models.SET_NULL)
    status = models.CharField(
        max_length=24, choices=STATUSES.items(), default=UNVERIFIED)

    start_time = models.DateTimeField()
    end_time = models.DateTimeField(blank=True, null=True, db_index=True)
    seconds_paused = models.PositiveIntegerField(default=0)
    pause_time = models.DateTimeField(blank=True, null=True)
    comments = models.TextField(blank=True)
    date_updated = models.DateTimeField(auto_now=True)

    hours = models.DecimalField(max_digits=11, decimal_places=5, default=0)

    objects = EntryManager()
    worked = EntryWorkedManager()
    no_join = models.Manager()

    class Meta:
        db_table = 'timepiece_entry'  # Using legacy table name
        ordering = ('-start_time',)
        verbose_name_plural = 'entries'
        permissions = (
            ('can_clock_in', 'Can use Pendulum to clock in'),
            ('can_pause', 'Can pause and unpause log entries'),
            ('can_clock_out', 'Can use Pendulum to clock out'),
            ('view_entry_summary', 'Can view entry summary page'),
            ('view_payroll_summary', 'Can view payroll summary page'),
            ('approve_timesheet', 'Can approve a verified timesheet'),
        )

    def __str__(self):
        return '%s on %s' % (self.user, self.project)

    def check_overlap(self, entry_b, **kwargs):
        """Return True if the two entries overlap."""
        consider_pause = kwargs.get('pause', True)
        entry_a = self
        # if entries are open, consider them to be closed right now
        if not entry_a.end_time or not entry_b.end_time:
            return False
        # Check the two entries against each other
        start_inside = entry_a.start_time > entry_b.start_time \
            and entry_a.start_time < entry_b.end_time
        end_inside = entry_a.end_time > entry_b.start_time \
            and entry_a.end_time < entry_b.end_time
        a_is_inside = entry_a.start_time > entry_b.start_time \
            and entry_a.end_time < entry_b.end_time
        b_is_inside = entry_a.start_time < entry_b.start_time \
            and entry_a.end_time > entry_b.end_time
        overlap = start_inside or end_inside or a_is_inside or b_is_inside
        if not consider_pause:
            return overlap
        else:
            if overlap:
                max_end = max(entry_a.end_time, entry_b.end_time)
                min_start = min(entry_a.start_time, entry_b.start_time)
                diff = max_end - min_start
                diff = diff.seconds + diff.days * 86400
                total = entry_a.get_total_seconds() + entry_b.get_total_seconds() - 1
                if total >= diff:
                    return True
            return False

    def is_overlapping(self):
        if self.start_time and self.end_time:
            entries = self.user.timepiece_entries.filter(
                Q(end_time__range=(self.start_time, self.end_time)) |
                Q(start_time__range=(self.start_time, self.end_time)) |
                Q(start_time__lte=self.start_time, end_time__gte=self.end_time)
            )

            totals = entries.aggregate(max=Max('end_time'), min=Min('start_time'))

            totals['total'] = 0
            for entry in entries:
                totals['total'] = totals['total'] + entry.get_total_seconds()

            totals['diff'] = totals['max'] - totals['min']
            totals['diff'] = totals['diff'].seconds + \
                totals['diff'].days * 86400

            if totals['total'] > totals['diff']:
                return True
            else:

django2use/works/timepiece/forms.py
import datetime
from dateutil.relativedelta import relativedelta
import time

from django import forms
from django.contrib.auth.models import User

from timepiece.fields import UserModelChoiceField

from timepiece.entries.models import Entry


DATE_FORM_FORMAT = '%Y-%m-%d'
INPUT_FORMATS = [DATE_FORM_FORMAT]


class TimepieceSplitDateTimeWidget(forms.SplitDateTimeWidget):

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('date_format', DATE_FORM_FORMAT)
        super(TimepieceSplitDateTimeWidget, self).__init__(*args, **kwargs)


class TimepieceSplitDateTimeField(forms.SplitDateTimeField):
    widget = TimepieceSplitDateTimeWidget


class TimepieceDateInput(forms.DateInput):

    def __init__(self, *args, **kwargs):
        kwargs['format'] = kwargs.get('format', DATE_FORM_FORMAT)
        super(TimepieceDateInput, self).__init__(*args, **kwargs)


class DateForm(forms.Form):
    from_date = forms.DateField(
        label='From', required=False, input_formats=INPUT_FORMATS,
        widget=TimepieceDateInput())
    to_date = forms.DateField(
        label='To', required=False, input_formats=INPUT_FORMATS,
        widget=TimepieceDateInput())

    def clean(self):
        from_date = self.cleaned_data.get('from_date', None)
        to_date = self.cleaned_data.get('to_date', None)
        if from_date and to_date and from_date > to_date:
            raise forms.ValidationError('The ending date must exceed the '
                                        'beginning date.')
        return self.cleaned_data

    def save(self):
        from_date = self.cleaned_data.get('from_date', '')
        to_date = self.cleaned_data.get('to_date', '')
        to_date = to_date + relativedelta(days=1) if to_date else to_date
        return (from_date, to_date)


class YearMonthForm(forms.Form):
    MONTH_CHOICES = [(i, time.strftime('%b', time.strptime(str(i), '%m')))
                     for i in range(1, 13)]
    month = forms.ChoiceField(choices=MONTH_CHOICES, label='')
    year = forms.ChoiceField(label='')

    def __init__(self, *args, **kwargs):
        super(YearMonthForm, self).__init__(*args, **kwargs)
        now = datetime.datetime.now()
        this_year = now.year
        this_month = now.month
        try:
            first_entry = Entry.no_join.values('end_time')\
                                       .order_by('end_time')[0]
        except IndexError:
            first_year = this_year
        else:
            first_year = first_entry['end_time'].year
        years = [(year, year) for year in range(first_year, this_year + 1)]
        self.fields['year'].choices = years
        initial = kwargs.get('initial')
        if initial:
            this_year = initial.get('year', this_year)
            this_month = initial.get('month', this_month)
        self.fields['year'].initial = this_year
        self.fields['month'].initial = this_month

    def save(self):
        now = datetime.datetime.now()
        this_year = now.year
        this_month = now.month
        month = int(self.cleaned_data.get('month', this_month))
        year = int(self.cleaned_data.get('year', this_year))
        from_date = datetime.datetime(year, month, 1)
        to_date = from_date + relativedelta(months=1)

        return (from_date, to_date)


class UserYearMonthForm(YearMonthForm):
    user = UserModelChoiceField(label='', queryset=None, required=False)

    def __init__(self, *args, **kwargs):
        super(UserYearMonthForm, self).__init__(*args, **kwargs)
        queryset = User.objects.exclude(timepiece_entries=None)\
                               .order_by('first_name')
        self.fields['user'].queryset = queryset

    def save(self):
        from_date, to_date = super(UserYearMonthForm, self).save()
        return (from_date, to_date, self.cleaned_data.get('user', None))

django2use/works/timepiece/templates/timepiece/base.html
<!doctype html>
{% load compress %}
{% load static %}
<html>
<head>
    <title>Timepiece: {% block title %}{% endblock title %}</title>
    <link rel="icon" type="image/png" href="{% static "images/icons/timepiece.png" %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    {% block javascript %}
    <script charset="utf-8" src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    {% comment %}
    .button() is in both bootstrap & jqueryui. Selectable depends on
    jqueryui's, and bootstrap's is not currently used, so we'll load
    jqueryui last so that it has precedence.
    {% endcomment %}
    <script charset="utf-8" src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
    <script charset="utf-8" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
    <script charset="utf-8" src="{% static "selectable/js/jquery.dj.selectable.js" %}"></script>
    {% endblock javascript %}

    {% if perms.crm.view_business %}  {# FIXME: Permission doesn't exist #}
        {{ quick_search_form.media.js }}
        <script charset="utf-8" src="{% static "timepiece/js/quick_search.js" %}"></script>
    {% endif %}
    <script charset="utf-8" src="{% static "timepiece/js/widgets.js" %}"></script>


    {% block css %}
        <link type="text/css" rel="stylesheet"
                href="//ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/smoothness/jquery-ui.css" />
    {% endblock css %}

    {% block staticfiles %}
        {% compress css %}
            <link rel="stylesheet" type="text/less"
                  href="{% static "timepiece/less/style.less" %}" />
        {% endcompress %}
    {% endblock staticfiles %}

    {% block extracss %}
    {% endblock extracss %}
</head>

<body id="{% block bodyid %}{% endblock bodyid %}">
    {% block navigation %}
        {% include "timepiece/navigation.html" %}
    {% endblock navigation %}

    <div id="content" class="container-fluid">
        {% block messages %}
            {% include "timepiece/messages.html" %}
        {% endblock messages %}

        {% if user.is_authenticated %}
            {% block breadcrumb %}
                <ul class="breadcrumb">
                    {% block crumbs %}
                        <li><a href="{% url 'dashboard' %}">Home</a></li>
                    {% endblock crumbs %}
                </ul>
            {% endblock breadcrumb %}
        {% endif %}

        {% block content %}
        {% endblock content %}
    </div>

    {% block footer %}
        <footer class="footer">
            <div class="container-fluid">
                <p class="pull-right">
                    <a href="https://github.com/caktus/django-timepiece/">Source</a>
                    |
                    <a href="http://www.caktusgroup.com/">Caktus Group</a>
                </p>
            </div>
        </footer>
    {% endblock footer %}

    <script charset="utf-8" src="{% static "timepiece/js/sticky_table_header.js" %}"></script>
    {% block extrajs %}
    {% endblock extrajs %}
</body>

</html>

django2use/works/timepiece/templates/timepiece/date_filters.html
<script>
    function update_dates(node) {
        var from_date = $("#id_from_date");
        var to_date = $("#id_to_date");
        from_date.val($(node).attr("from_date"));
        to_date.val($(node).attr("to_date"));
        $("#{{ form_id }}").submit();
    };
</script>

<ul class="date-filters">
    {% for filter_category, filter_list in filters.items %}
        <li>
            <ul>
                <li class="label">{{ filter_category }}</li>
                {% for label, from_date, to_date in filter_list %}
                    <li><a href="javascript:void(0);" class="date-filter" from_date="{{ from_date }}" to_date="{{ to_date }}" onclick="update_dates(this);">{{ label }}</a></li>
                {% endfor %}
            </ul>
        </li>
    {% endfor %}
</ul>

django2use/works/timepiece/templates/timepiece/delete_object.html
{% extends "timepiece/base.html" %}

{% block title %}
    Delete {{ object }}
{% endblock title %}

{% block content %}
    <div class="row-fluid">
        <div class="span12">
            {% if object.get_name_or_username %}
                <h3>Are you sure you want to delete {{ object.get_name_or_username }}?</h3>
            {% else %}
                <h3>Are you sure you want to delete {{ object }}?</h3>
            {% endif %}
            <form method="post" action="">
                {% csrf_token %}
                <input type="hidden" name="delete" value="delete" />
                <input type="submit" class="btn btn-danger" value="Delete" />
                <input type="button" class="btn" value="Do Not Delete" onclick="history.back(-1)" />
            </form>
        </div>
    </div>
{% endblock content %}

django2use/works/timepiece/templates/timepiece/extra_nav.html
{% comment %}
You can override this template to include extra, custom items in the timepiece
navigation bar.

We use Bootstrap styling so you can use both plain navigation items and
dropdown navigation items.

If you add many items, you may want to adjust the width at which the navbar
collapses by setting the variable @navbarCollapseWidth in your less file.

For example:

<!-- A dropdown menu item. -->
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Paste Bin <b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li><a href="{% url 'create_paste' %}">Create Paste</a></li>
        <li><a href="{% url 'list_pastes' %}">View Pastes</a></li>
    </ul>
</li>

<!-- A plain menu item. -->
<li>
    <a href="http://example.com/">Example</a>
</li>

{% endcomment %}

django2use/works/timepiece/templates/timepiece/messages.html
<div id="alerts">
    {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
            <a class="close" data-dismiss="alert" href="#">x</a>
            {{ message }}
        </div>
    {% endfor %}
</div>

django2use/works/timepiece/templates/timepiece/navigation-crm.html
{% load timepiece_tags %}

{# FIXME: Some permissions don't exist #}
{% if perms.crm.view_project or perms.auth.view_user or perms.crm.view_business or perms.contracts.add_project_contract %}
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">CRM <b class="caret"></b></a>
        <ul class="dropdown-menu">
            {% if perms.crm.view_project %}
                <li><a href="{% url 'list_projects' %}">Projects</a></li>
            {% endif %}
            {% if perms.auth.view_user %}  {# FIXME: Permission doesn't exist #}
                <li><a href="{% url 'list_users' %}">Users</a></li>
            {% endif %}
            {% if perms.crm.view_business %}  {# FIXME: Permission doesn't exist #}
                <li><a href="{% url 'list_businesses' %}">Businesses</a></li>
            {% endif %}
            {% if perms.contracts.add_project_contract %}
                <li><a href="{% url 'list_contracts' %}">Contracts</a></li>
            {% endif %}
        </ul>
    </li>
{% endif %}

django2use/works/timepiece/templates/timepiece/navigation-management.html
{% load timepiece_tags %}

{# FIXME: Some of those permissions don't exist #}
{% if perms.entries.can_clock_in or perms.entries.view_entry_summary or perms.entries.view_payroll_summary or perms.contracts.change_entrygroup or user.is_staff %}
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Management <b class="caret"></b></a>
        <ul class="dropdown-menu">
            {% if perms.entries.view_entry_summary %}  {# FIXME: permission doesn't exist #}
                <li><a href="{% url 'report_billable_hours' %}">Billable Hours</a></li>
                <li><a href="{% url 'report_hourly' %}">Hourly</a></li>
            {% endif %}
            {% if perms.entries.view_payroll_summary %}
                <li><a href="{% url 'report_payroll_summary' %}">Payroll Summary</a></li>
                <li><a href="{% url 'report_productivity' %}">Productivity</a></li>
                <li><a href="{% url 'report_estimation_accuracy' %}">Estimation Accuracy</a></li>
                {% if user.is_staff or perms.contracts.change_entrygroup or perms.entries.can_clock_in %}
                    <li class="divider"></li>
                {% endif %}
            {% endif %}
            {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
            {% endif %}
            {% if perms.contracts.change_entrygroup %}
                <li><a href="{% url 'list_outstanding_invoices' %}">Invoices</a></li>
            {% endif %}
            {% if perms.entries.can_clock_in %}
                <li><a href="{% url 'view_schedule' %}">Weekly Schedule</a></li>
            {% endif %}
        </ul>
    </li>
{% endif %}

django2use/works/timepiece/templates/timepiece/navigation-quick-clock-in.html
{% load timepiece_tags %}
{% block quick-clock-in %}
    {% if perms.entries.can_clock_in %}
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-time icon-white"> </i><b class="caret"></b> </a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'clock_in' %}">Clock in...</a></li>
                <li><a href="{% url 'create_entry' %}">Add Entry...</a></li>
                {% if work_projects %}<li class="divider"></li>{% endif %}
                {% for project in work_projects %}
                    <li><a href="{% url 'clock_in' %}?project={{ project.id }}">{{ project }}</a></li>
                {% endfor %}
                {% if leave_projects %}<li class="divider"></li>{% endif %}
                {% for project in leave_projects %}
                    <li><a href="{% url 'clock_in' %}?project={{ project.id }}">{{ project }}</a></li>
                {% endfor %}
            </ul>
        </li>
    {% endif %}
{% endblock quick-clock-in %}

django2use/works/timepiece/templates/timepiece/navigation-timesheet.html
{% load timepiece_tags %}

{% if perms.entries.add_entry %}
    <li><a href="{% url 'view_user_timesheet' request.user.pk %}">Time Sheet</a></li>
{% endif %}

django2use/works/timepiece/templates/timepiece/navigation.html
{% load timepiece_tags %}

<div class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">

        <div id="full-nav" class="container-fluid">
            {% block navbar-left %}
                <a class="brand" href="/">Timepiece</a>
                <ul class="nav pull-left">
                    {% include "timepiece/navigation-quick-clock-in.html" %}
                    {% include "timepiece/navigation-timesheet.html" %}
                    {% include "timepiece/navigation-crm.html" %}
                    {% include "timepiece/navigation-management.html" %}

                    {% include "timepiece/extra_nav.html" %}
                </ul>
            {% endblock navbar-left %}

            {% block navbar-right %}
                {% if user.is_authenticated %}
                    <ul class="nav pull-right">
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user icon-white"></i> {{ user.first_name }} <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'edit_settings' %}">Settings</a></li>
                                <li><a href="{% url 'change_password' %}">Change Password</a></li>
                                <li class="divider"></li>
                                <li><a href="{% url 'auth_logout' %}">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                {% else %}
                    <a class="btn btn-primary pull-right" href="{% url 'auth_login' %}">Login</a>
                {% endif %}

                {% block quick-search %}
                    {% if perms.crm.view_business %}
                        <form id="quick_search" class="navbar-search pull-right" action="{% url 'quick_search' %}" method="post" accept-charset="utf-8">
                            {% csrf_token %}
                            {{ quick_search_form.quick_search }}
                        </form>
                        <script>
                            $(document).ready(function() {
                                var quick_search = $('#quick_search :input[name=quick_search_0]');
                                quick_search.bind('djselectableselect', function(event, ui) {
                                    $(this).parents('form').submit();
                                });
                            });
                        </script>
                    {% endif %}
                {% endblock quick-search %}
            {% endblock navbar-right %}
        </div>

        <div id="collapsed-nav" class="container-fluid">
            <a class="brand" href="/">Timepiece</a>

            {% if user.is_authenticated %}
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
            {% endif %}

            <div class="nav-collapse">
                <ul class="nav">
                    {% if perms.entries.add_entry %}
                        <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
                        <li><a href="{% url 'view_user_timesheet' request.user.pk %}">Time Sheet</a></li>
                        <li><a href="{% url 'view_schedule' %}">Schedule</a></li>
                        <li><a href="{% url 'create_entry' %}">Add Entry</a></li>
                        <li><a href="{% url 'auth_logout' %}">Logout</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>

django2use/works/timepiece/templates/timepiece/pagination.html
{% load i18n %}
{% load timepiece_tags %}
<div class="pagination">
  <ul>
    {% if page_obj.has_previous %}
      <li>
        {% with base_url="?" %}
          <a href="{{ base_url|add_parameters:request.GET }}&page={{ page_obj.previous_page_number }}"
             class="prev">&laquo; {% trans "previous" %}</a>
        {% endwith %}
      </li>
    {% else %}
      <li class="disabled">
        <a>&laquo; {% trans "previous" %}</a>
      </li>
    {% endif %}

    {% for page_num in paginator.page_range %}
      {% ifequal page_num page_obj.number %}
        <li class="active">
          <a>{{ page_num }}</a>
        </li>
      {% else %}
        <li>
          {% with base_url="?" %}
            <a href="{{ base_url|add_parameters:request.GET }}&page={{ page_num }}">{{ page_num }}</a>
          {% endwith %}
        </li>
      {% endifequal %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li>
        {% with base_url="?" %}
          <a href="{{ base_url|add_parameters:request.GET }}&page={{ page_obj.next_page_number }}"
             class="next">{% trans "next" %} &raquo;</a>
        {% endwith %}
      </li>
    {% else %}
      <li class="disabled">
        <a class="disabled next">{% trans "next" %} &raquo;</a>
      </li>
    {% endif %}
  </ul>
</div>

django2use/works/timepiece/templates/timepiece/quick_search.html
{% extends "timepiece/base.html" %}

{% block title %}Search Results{% endblock title %}

{% block content %}
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-error">{{ error }}</div>
            {% endfor %}
        {% endfor %}
    {% endif %}

    <form class="form-inline" method="post" action="{% url 'quick_search' %}">
        {% csrf_token %}
        {{ form.quick_search }}
        <button class="btn">Search</button>
    </form>
{% endblock content %}