django2use/panel/models.py
from django.db import models

from django2use.basic.models import *
from django2use.osint.models import *

from django.utils import timezone

#*********************************************************************

WEBSITE_TYPEs = (
    ('wp', "WordPress"),

    ('mg', "Magento"),
    ('ps', "PrestaShop"),
)

######################################################################

class Hosting(models.Model):
    owner   = models.ForeignKey(Organism, related_name='hosting', on_delete=models.CASCADE)
    alias   = models.CharField(max_length=64)

    target  = models.URLField(blank=True)
    pseudo  = models.CharField(max_length=256,blank=True)
    passwd  = models.CharField(max_length=256,blank=True)
    domain  = models.ManyToManyField(Domain, related_name='hosting', blank=True)

    def __str__(self): return str(self.alias)

#*********************************************************************

class Website(models.Model):
    owner   = models.ForeignKey(Organism, related_name='websites', on_delete=models.CASCADE)
    alias   = models.CharField(max_length=64)

    frame   = models.CharField(max_length=24,choices=WEBSITE_TYPEs,blank=True)
    where   = models.ForeignKey(Hosting, related_name='websites', on_delete=models.CASCADE)

    target  = models.URLField(blank=True)
    pseudo  = models.CharField(max_length=256,blank=True)
    passwd  = models.CharField(max_length=256,blank=True)
    #domain  = models.ManyToManyField(Domain, related_name='hosting', blank=True)

    def __str__(self): return str(self.alias)

django2use/panel/views/EDIT.py
from django2use.helpers import *

#*******************************************************************************

from django2use.basic.forms import *

################################################################################

def gentella_html(request):
    context = {}
    # The template to be loaded as per gentelella.
    # All resource paths for gentelella end in .html.

    # Pick out the html file name from the url. And load that template.
    load_template = request.path.split('/')[-1]
    template = loader.get_template('app/' + load_template)
    return HttpResponse(template.render(context, request))

#*******************************************************************************

class HomeView(TemplateView):
    template_name = 'studio/editor.html'

################################################################################

class IPFS_View(TemplateView):
    template_name = 'editor/ipfs.html'

#*******************************************************************************

class JSON_View(TemplateView):
    template_name = 'editor/json.html'

#*******************************************************************************

class RDFS_View(TemplateView):
    template_name = 'editor/rdfs.html'

#*******************************************************************************

class UploadsView(TemplateView):
    template_name = 'editor/uploads.html'

django2use/panel/templates/website/conf.html
{% extends 'layout/form.html' %}
{% load static %}

{% block title %}
Website - Cloud APIs
{% endblock title %}

{% block custom_js_css_link %}
{% endblock custom_js_css_link %}

{% block form_actions %}
<button type="submit" class="btn btn-success">Save</button>
{% endblock %}

{% block page_level_script %}
<script src="{% static 'assets/js/scrollspyNav.js' %}"></script>
{% endblock page_level_script %}

django2use/panel/templates/website/edit.html
{% extends 'layout/form.html' %}
{% load static %}

{% block title %}
Website - Update
{% endblock title %}

{% block custom_js_css_link %}
{% endblock custom_js_css_link %}

{% block form_actions %}
<button type="submit" class="btn btn-success">Save</button>
{% endblock %}

{% block page_level_script %}
<script src="{% static 'assets/js/scrollspyNav.js' %}"></script>
{% endblock page_level_script %}

django2use/panel/templates/website/list.html
{% extends 'layout/list.html' %}
{% load static %}

{% block title %}
Website - Listing
{% endblock title %}

{% block breadcrumb_title %}List all websites{% endblock %}

{% block grid_actions %}
<div class="multiple_targets_button" style="visibility: hidden;">
  <a class="btn btn-outline-danger mb-2 float-right" href="#" onclick="deleteMultipleTargets()">Delete Multiple Targets</a>
  <a class="btn btn-outline-info mb-2 float-right" href="#" onclick="scanMultipleTargets()">Scan Multiple Targets</a>
</div>
{% endblock %}

{% block grid_column %}
          <th class="checkbox-column">Alias</th>
          <th>Owner</th>
          <th>Frame</th>
          <th>Where</th>
          <th>Target</th>
          <th>Pseudo</th>
          <th class="text-center">Action</th>
{% endblock %}

{% block grid_record %}
<td class="checkbox-column">
    <a href="{% url 'organism_read' entry.pk %}">
        {{ entry.alias }}
    </a>
</td>
<td>{{ entry.owner }}</td>
<td>{{ entry.get_frame_display }}</td>
<td class="checkbox-column">
    <a href="{% url 'hosting_read' entry.pk %}">
        {{ entry.where }}
    </a>
</td>
<td>{{ entry.target }}</td>
<td>{{ entry.pseudo }}</td>
{% endblock %}

{% block grid_action %}
{% if entry %}
<a href="{% url 'organism_edit' entry.pk %}" class="bs-tooltip open-domain" data-placement="top" title="" data-original-title="Update target">
  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather table-edit feather-edit-2">
    <path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path>
  </svg>
</a>
<!--
<a href="{% url 'organism_edit' entry.pk %}" class="bs-tooltip btnDelDomain" href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Delete target">
  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather table-delete feather-x-circle">
    <circle cx="12" cy="12" r="10"></circle>
    <line x1="15" y1="9" x2="9" y2="15"></line>
    <line x1="9" y1="9" x2="15" y2="15"></line>
  </svg>
</a>
-->
{% endif %}
{% endblock %}

django2use/panel/templates/website/make.html
{% extends 'layout/form.html' %}
{% load static %}

{% block title %}
Website - Add new
{% endblock %}

{% block custom_js_css_link %}
{% endblock custom_js_css_link %}

{% block form_actions %}
<button type="submit" class="btn btn-success">Save</button>
{% endblock %}

{% block page_level_script %}
<script src="{% static 'assets/js/scrollspyNav.js' %}"></script>
{% endblock %}

django2use/panel/templates/website/scan.html
{% extends 'layout/form.html' %}
{% load static %}

{% block title %}
Website - Scan
{% endblock %}

{% block custom_js_css_link %}
{% endblock custom_js_css_link %}

{% block form_name %}Start a new Scan{% endblock %}

{% block form_actions %}
<button type="submit" class="btn btn-success">Start</button>
{% endblock %}

{% block form_before %}
<div class="row">
   <div class='col-md-6'>
{% endblock %}

{% block form_after %}
    </div>
    <div class="col-md-6">
       <div id="datetimepicker12"></div>
    </div>
</div>
{% endblock %}

{% block page_level_script %}
<script src="{% static 'gentelella/ext/jQuery-Smart-Wizard/js/jquery.smartWizard.js' %}"></script>
<script type="text/javascript">
   $(function () {
       $('#datetimepicker12').datetimepicker({
           inline: true,
           sideBySide: true
       });
       $("input[name='target']").addClass('form-control');
       $("select[name='method']").addClass('form-control');
       $("input[name='emails']").addClass('form-control');
       $("input[name='notify']").addClass('form-control');
   });
</script>
{% endblock %}