django2use/works/timepiece/contracts/urls.py
from django.conf.urls import url

from timepiece.contracts import views


urlpatterns = [
    # Contracts
    url(r'^contract/$',
        views.ContractList.as_view(),
        name='list_contracts'),
    url(r'^contract/(?P<contract_id>\d+)/$',
        views.ContractDetail.as_view(),
        name='view_contract'),

    # Invoices
    url(r'invoice/$',
        views.ListInvoices.as_view(),
        name='list_invoices'),
    url(r'invoice/outstanding/$',
        views.list_outstanding_invoices,
        name='list_outstanding_invoices'),
    url(r'invoice/create/$',
        views.create_invoice,
        name='create_invoice'),
    url(r'invoice/(?P<invoice_id>\d+)/$',
        views.InvoiceDetail.as_view(),
        name='view_invoice'),
    url(r'invoice/(?P<invoice_id>\d+)/csv/$',
        views.InvoiceDetailCSV.as_view(),
        name='view_invoice_csv'),
    url(r'invoice/(?P<invoice_id>\d+)/entries/$',
        views.InvoiceEntriesDetail.as_view(),
        name='view_invoice_entries'),
    url(r'invoice/(?P<invoice_id>\d+)/entries/(?P<entry_id>\d+)/remove/$',
        views.delete_invoice_entry,
        name='delete_invoice_entry'),
    url(r'invoice/(?P<invoice_id>\d+)/edit/$',
        views.InvoiceEdit.as_view(),
        name='edit_invoice'),
    url(r'invoice/(?P<invoice_id>\d+)/delete/$',
        views.InvoiceDelete.as_view(),
        name='delete_invoice'),
]

django2use/works/timepiece/urls.py
from django.conf.urls import include, url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView


urlpatterns = [
    # Redirect the base URL to the dashboard.
    url(r'^$', RedirectView.as_view(url=reverse_lazy('dashboard'), permanent=False)),

    url('', include('timepiece.crm.urls')),
    url('', include('timepiece.contracts.urls')),
    url('', include('timepiece.entries.urls')),
    url('', include('timepiece.reports.urls')),
]

django2use/works/timepiece/contracts/models.py
from collections import OrderedDict
import datetime

from dateutil.relativedelta import relativedelta

from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Sum
from django.db.models.expressions import F, Func, Value
from django.template.loader import render_to_string
from django.utils.encoding import python_2_unicode_compatible

from timepiece import utils
from timepiece.entries.models import Entry


@python_2_unicode_compatible
class ProjectContract(models.Model):
    STATUS_UPCOMING = 'upcoming'
    STATUS_CURRENT = 'current'
    STATUS_COMPLETE = 'complete'
    CONTRACT_STATUS = OrderedDict((
        (STATUS_UPCOMING, 'Upcoming'),
        (STATUS_CURRENT, 'Current'),
        (STATUS_COMPLETE, 'Complete'),
    ))

    PROJECT_UNSET = 0  # Have to set existing contracts to something...
    PROJECT_FIXED = 1
    PROJECT_PRE_PAID_HOURLY = 2
    PROJECT_POST_PAID_HOURLY = 3
    PROJECT_TYPE = OrderedDict((   # UNSET is not an option
        (PROJECT_FIXED, 'Fixed'),
        (PROJECT_PRE_PAID_HOURLY, 'Pre-paid Hourly'),
        (PROJECT_POST_PAID_HOURLY, 'Post-paid Hourly'),
    ))

    name = models.CharField(max_length=255)
    projects = models.ManyToManyField('crm.Project', related_name='contracts')
    start_date = models.DateField()
    end_date = models.DateField()
    status = models.CharField(
        choices=CONTRACT_STATUS.items(), default=STATUS_UPCOMING, max_length=32)
    type = models.IntegerField(choices=PROJECT_TYPE.items())

    class Meta:
        ordering = ('-end_date',)
        verbose_name = 'contract'
        db_table = 'timepiece_projectcontract'  # Using legacy table name.

    def __str__(self):
        return self.name

    def get_admin_url(self):
        return reverse('admin:contracts_projectcontract_change', args=[self.pk])

    def get_absolute_url(self):
        return reverse('view_contract', args=[self.pk])

    def get_noncontract_entries(self, entries):
        """
        Given a set of entries, exclude those included in any contract affiliated
        with any project associated with this contract.
        """
        contracts = []
        for project in self.projects.all():
            contracts.extend(project.contracts.all())

        for contract in contracts:
            entries.exclude(
                project__in=contract.projects.all(),
                start_time__gte=contract.start_date,
                end_time__lt=contract.end_date + relativedelta(days=1)
                )
        return entries

    @property
    def pre_launch_entries(self):
        entries = Entry.objects.filter(
            project__in=self.projects.all(),
            start_time__lt=self.start_date,)
        return self.get_noncontract_entries(entries)

    @property
    def entries(self):
        """
        All Entries worked on projects in this contract during the contract
        period.
        """
        return Entry.objects.filter(
            project__in=self.projects.all(),
            start_time__gte=self.start_date,
            end_time__lt=self.end_date + relativedelta(days=1))

    @property
    def post_launch_entries(self):
        """
        All Entries worked on projects in this contract after the contract
        period.
        """
        entries = Entry.objects.filter(
            project__in=self.projects.all(),
            start_time__gt=self.end_date + relativedelta(days=1),)
        return self.get_noncontract_entries(entries)

    def contracted_hours(self, approved_only=True):
        """Compute the hours contracted for this contract.
        (This replaces the old `num_hours` field.)

        :param boolean approved_only: If true, only include approved
            contract hours; if false, include pending ones too.
        :returns: The sum of the contracted hours, subject to the
            `approved_only` parameter.
        :rtype: Decimal
        """

        qset = self.contract_hours
        if approved_only:
            qset = qset.filter(status=ContractHour.APPROVED_STATUS)
        result = qset.aggregate(sum=Sum('hours'))['sum']
        return result or 0

    def pending_hours(self):
        """Compute the contract hours still in pending status"""
        qset = self.contract_hours.filter(status=ContractHour.PENDING_STATUS)
        result = qset.aggregate(sum=Sum('hours'))['sum']
        return result or 0

    @property
    def hours_assigned(self):
        """Total assigned hours for this contract."""
        if not hasattr(self, '_assigned'):
            # TODO put this in a .extra w/a subselect
            assignments = self.assignments.aggregate(s=Sum('num_hours'))
            self._assigned = assignments['s'] or 0
        return self._assigned or 0

    @property
    def hours_remaining(self):
        return self.contracted_hours() - self.hours_worked

    @property
    def pre_launch_hours_worked(self):
        """Number of billable hours worked before the contract start date."""
        if not hasattr(self, '_worked_pre_launch'):
            # TODO put this in a .extra w/a subselect
            entries = self.pre_launch_entries.filter(activity__billable=True)
            self._worked_pre_launch = entries.aggregate(s=Sum('hours'))['s'] or 0
        return self._worked_pre_launch or 0

    @property
    def post_launch_hours_worked(self):
        """Number of billable hours worked after the contract end date."""
        if not hasattr(self, '_worked_post_launch'):
            # TODO put this in a .extra w/a subselect
            entries = self.post_launch_entries.filter(activity__billable=True)
            self._worked_post_launch = entries.aggregate(s=Sum('hours'))['s'] or 0
        return self._worked_post_launch or 0

    @property
    def hours_worked(self):
        """Number of billable hours worked on the contract."""
        if not hasattr(self, '_worked'):
            # TODO put this in a .extra w/a subselect
            entries = self.entries.filter(activity__billable=True)
            self._worked = entries.aggregate(s=Sum('hours'))['s'] or 0
        return self._worked or 0

    @property
    def nonbillable_hours_worked(self):
        """Number of non-billable hours worked on the contract."""
        if not hasattr(self, '_nb_worked'):
            # TODO put this in a .extra w/a subselect
            entries = self.entries.filter(activity__billable=False)
            self._nb_worked = entries.aggregate(s=Sum('hours'))['s'] or 0
        return self._nb_worked or 0

    @property
    def fraction_hours(self):
        """Fraction of contracted hours that have been worked.  E.g.
        if 50 hours have been worked of 100 contracted, value is 0.5.
        """
        if self.contracted_hours():
            return float(self.hours_worked) / float(self.contracted_hours())
        return 0.0

    @property
    def fraction_schedule(self):
        """If contract status is current, return the current date as a
        fraction of the scheduled period - e.g. if the contract period is
        June 1 to July 31, and today is July 1, then the value is
        about 0.5.

        If the contract status is not current, or either the start or end
        date is not set, returns 0.0
        """
        if not all([self.status == ProjectContract.STATUS_CURRENT,
                    bool(self.start_date),
                    bool(self.end_date)]):
            return 0.0
        contract_period = (self.end_date - self.start_date).days
        if contract_period <= 0.0:
            return 0.0
        days_elapsed = (datetime.date.today() - self.start_date).days
        if days_elapsed <= 0.0:
            return 0.0
        return float(days_elapsed) / contract_period


@python_2_unicode_compatible
class ContractHour(models.Model):
    PENDING_STATUS = 1
    APPROVED_STATUS = 2
    CONTRACT_HOUR_STATUS = (
        (PENDING_STATUS, 'Pending'),  # default
        (APPROVED_STATUS, 'Approved'),
    )

    hours = models.DecimalField(
        max_digits=8, decimal_places=2, default=0)
    contract = models.ForeignKey(
        ProjectContract, related_name='contract_hours')
    date_requested = models.DateField()
    date_approved = models.DateField(blank=True, null=True)
    status = models.IntegerField(
        choices=CONTRACT_HOUR_STATUS, default=PENDING_STATUS)
    notes = models.TextField(blank=True)

    class Meta(object):
        verbose_name = 'contracted hours'
        verbose_name_plural = verbose_name
        db_table = 'timepiece_contracthour'  # Using legacy table name.

    def __str__(self):
        return "{} on {} ({})".format(
            self.hours, self.contract, self.get_status_display())

    def __init__(self, *args, **kwargs):
        super(ContractHour, self).__init__(*args, **kwargs)
        # Save the current values so we can report changes later
        self._original = {
            'hours': self.hours,
            'notes': self.notes,
            'status': self.status,
            'get_status_display': self.get_status_display(),
            'date_requested': self.date_requested,
            'date_approved': self.date_approved,
            'contract': self.contract if self.contract_id else None,
        }

    def get_absolute_url(self):
        return reverse('admin:contracts_contracthour_change', args=[self.pk])

    def clean(self):
        # Note: this is called when editing in the admin, but not otherwise
        if self.status == self.PENDING_STATUS and self.date_approved:
            raise ValidationError(
                "Pending contracthours should not have an approved date, did "
                "you mean to change status to approved?"
            )

    def _send_mail(self, subject, ctx):
        # Don't go to the work unless we have a place to send it

django2use/works/timepiece/contracts/forms.py
from dateutil.relativedelta import relativedelta

from django import forms

from timepiece import utils
from timepiece.contracts.models import EntryGroup
from timepiece.crm.models import Attribute
from timepiece.forms import DateForm


class InvoiceForm(forms.ModelForm):

    class Meta:
        model = EntryGroup
        fields = ('status', 'number', 'comments')

    def save(self, commit=True):
        instance = super(InvoiceForm, self).save(commit=False)
        instance.project = self.initial['project']
        instance.user = self.initial['user']
        from_date = self.initial['from_date']
        to_date = self.initial['to_date']
        instance.start = from_date
        instance.end = to_date
        instance.save()
        return instance


class OutstandingHoursFilterForm(DateForm):
    statuses = forms.ModelMultipleChoiceField(
        queryset=Attribute.objects.none(), required=False,
        widget=forms.CheckboxSelectMultiple())

    def __init__(self, *args, **kwargs):
        super(OutstandingHoursFilterForm, self).__init__(*args, **kwargs)

        # Check all statuses by default.
        statuses = Attribute.statuses.all()
        self.fields['statuses'].queryset = statuses
        self.fields['statuses'].initial = statuses

        month_start = utils.get_month_start().date()
        self.fields['to_date'].required = True
        self.fields['to_date'].initial = month_start - relativedelta(days=1)
        self.fields['from_date'].initial = None

    def get_from_date(self):
        if self.is_valid():
            return self.cleaned_data['from_date']
        return self.fields['from_date'].initial

    def get_to_date(self):
        if self.is_valid():
            return self.cleaned_data['to_date']
        return self.fields['to_date'].initial

    def get_statuses(self):
        if self.is_valid():
            return self.cleaned_data['statuses']
        return self.fields['statuses'].initial

    def get_form_data(self):
        return {
            'to_date': self.get_to_date(),
            'from_date': self.get_from_date(),
            'statuses': self.get_statuses()
        }

django2use/works/timepiece/templates/timepiece/contract/base.html
{% extends "timepiece/base.html" %}

{% block crumbs %}
    {{ block.super }}
    <li><span class="divider">/</span> <a href="{% url 'list_contracts' %}">Contracts</a></li>
{% endblock crumbs %}

django2use/works/timepiece/templates/timepiece/contract/list.html
{% extends 'timepiece/contract/base.html' %}

{% load static %}
{% load timepiece_tags %}

{% block title %}Current Contracts{% endblock title %}
{% block bodyid %}contracts{% endblock bodyid %}

{% block extrajs %}
    <script>
        var max_work_fraction = {{ max_work_fraction }};
        var max_schedule_fraction = {{ max_schedule_fraction }};
    </script>
    <script charset="utf-8" src="{% static "timepiece/js/contract.js" %}"></script>
{% endblock extrajs %}

{% block content %}
    <div class="row-fluid">
        <div class="span12">

        <ul class="nav nav-tabs">
          <li role="presentation" class="active"><a href="#current" data-toggle="tab">Current Contracts</a></li>
          <li role="presentation"><a href="#pending" data-toggle="tab">Pending Contracts</a></li>
          <li role="presentation"><a href="#completed" data-toggle="tab">Completed Contracts</a></li>
        </ul>
    <div class="tab-content">
        <div class="tab-pane fade in active" id="current">
            <h2 class="page-title">Current Contracts</h2>
            <table class="table table-bordered table-striped table-condensed contracts">
                <thead>
                    <tr>
                        <th rowspan="2">Name</th>
                        <th rowspan="2">Start Date</th>
                        <th rowspan="2">End Date</th>
                        <th rowspan="2">Contract Hours</th>
                        <th colspan="2">Hours Worked</th>
                        <th rowspan="2" class="hidden-phone">Progress: days elapsed/hours worked</th>
                        <th rowspan="2">Contract Type</th>
                    </tr>
                    <tr>
                        <th>Billable</th>
                        <th>Non-billable</th>
                    </tr>
                </thead>
                <tbody>
                    {% for contract in contracts %}
                        {% if contract.end_date < today %}
                            <tr class="expired" title="This contract has expired.">
                        {% elif contract.end_date < warning_date %}
                            <tr class="expiring-soon" title="This contract will expire in less than 2 weeks.">
                        {% else %}
                            <tr>
                        {% endif %}
                            <td><a href="{% url 'view_contract' contract.id %}">{{ contract.name }}</a></td>
                            <td class="nowrap">{{ contract.start_date|date:'M j, Y' }}</td>
                            <td class="nowrap{% if contract.end_date < today %} past{% endif %}">
                                {{ contract.end_date|date:'M j, Y' }}
                                {% if contract.end_date >= today and contract.end_date < warning_date %}
                                    <i class="icon-warning-sign"></i>
                                {% endif %}
                            </td>
                            <td class="nowrap hours">
                                {{ contract.contracted_hours|floatformat:2 }}
                                {% if contract.pending_hours %}
                                    <span class="pending_hours">(+{{ contract.pending_hours|floatformat:2 }})</span>
                                {%  endif %}
                            </td>
                            <td class="nowrap hours">{{ contract.hours_worked|floatformat:2 }} ({% widthratio contract.hours_worked contract.contracted_hours 100 %}%)</td>
                            <td class="nowrap hours">{{ contract.nonbillable_hours_worked|floatformat:2 }}</td>
                            <td class="hidden-phone">
                                <div class="project-bar" style="width: 100%"
                                    data-fraction="{{ contract.fraction_schedule }}"></div>
                                <div class="project-bar" style="width: 100%"
                                    data-fraction="{{ contract.fraction_hours }}"></div>
                            </td>
                            <td class="nowrap">{{ contract.get_type_display }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="tab-pane fade" id="pending">
            <h2 class="page-title">Pending Contracts</h2>
            <table class="table table-bordered table-striped table-condensed contracts">
                <thead>
                    <tr>
                        <th rowspan="2">Name</th>
                        <th rowspan="2">Start Date</th>
                        <th rowspan="2">End Date</th>
                        <th rowspan="2">Contract Hours</th>
                        <th colspan="2">Hours Worked</th>
                        <th rowspan="2" class="hidden-phone">Progress: days elapsed/hours worked</th>
                        <th rowspan="2">Contract Type</th>
                    </tr>
                    <tr>
                        <th>Billable</th>
                        <th>Non-billable</th>
                    </tr>
                </thead>
                <tbody>
                    {% for contract in projects_pending %}
                        {% if contract.end_date < today %}
                            <tr class="expired" title="This contract has expired.">
                        {% elif contract.end_date < warning_date %}
                            <tr class="expiring-soon" title="This contract will expire in less than 2 weeks.">
                        {% else %}
                            <tr>
                        {% endif %}
                            <td><a href="{% url 'view_contract' contract.id %}">{{ contract.name }}</a></td>
                            <td class="nowrap">{{ contract.start_date|date:'M j, Y' }}</td>
                            <td class="nowrap{% if contract.end_date < today %} past{% endif %}">
                                {{ contract.end_date|date:'M j, Y' }}
                                {% if contract.end_date >= today and contract.end_date < warning_date %}
                                    <i class="icon-warning-sign"></i>
                                {% endif %}
                            </td>
                            <td class="nowrap hours">
                                {{ contract.contracted_hours|floatformat:2 }}
                                {% if contract.pending_hours %}
                                    <span class="pending_hours">(+{{ contract.pending_hours|floatformat:2 }})</span>
                                {%  endif %}
                            </td>
                            <td class="nowrap hours">{{ contract.hours_worked|floatformat:2 }} ({% widthratio contract.hours_worked contract.contracted_hours 100 %}%)</td>
                            <td class="nowrap hours">{{ contract.nonbillable_hours_worked|floatformat:2 }}</td>
                            <td class="hidden-phone">
                                <div class="project-bar" style="width: 100%"
                                    data-fraction="{{ contract.fraction_schedule }}"></div>
                                <div class="project-bar" style="width: 100%"
                                    data-fraction="{{ contract.fraction_hours }}"></div>
                            </td>
                            <td class="nowrap">{{ contract.get_type_display }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="tab-pane fade" id="completed">
            <h2 class="page-title">Completed Contracts</h2>
            <table class="table table-bordered table-striped table-condensed contracts">
                <thead>
                    <tr>
                        <th rowspan="2">Name</th>
                        <th rowspan="2">Start Date</th>
                        <th rowspan="2">End Date</th>
                        <th rowspan="2">Contract Hours</th>
                        <th colspan="2">Hours Worked</th>
                        <th rowspan="2" class="hidden-phone">Progress: days elapsed/hours worked</th>
                        <th rowspan="2">Contract Type</th>
                    </tr>
                    <tr>
                        <th>Billable</th>
                        <th>Non-billable</th>
                    </tr>
                </thead>
                <tbody>
                    {% for contract in projects_complete %}
                        {% if contract.end_date < today %}
                            <tr class="expired" title="This contract has expired.">
                        {% elif contract.end_date < warning_date %}
                            <tr class="expiring-soon" title="This contract will expire in less than 2 weeks.">
                        {% else %}
                            <tr>
                        {% endif %}
                            <td><a href="{% url 'view_contract' contract.id %}">{{ contract.name }}</a></td>
                            <td class="nowrap">{{ contract.start_date|date:'M j, Y' }}</td>
                            <td class="nowrap{% if contract.end_date < today %} past{% endif %}">
                                {{ contract.end_date|date:'M j, Y' }}
                                {% if contract.end_date >= today and contract.end_date < warning_date %}
                                    <i class="icon-warning-sign"></i>
                                {% endif %}
                            </td>
                            <td class="nowrap hours">
                                {{ contract.contracted_hours|floatformat:2 }}
                                {% if contract.pending_hours %}
                                    <span class="pending_hours">(+{{ contract.pending_hours|floatformat:2 }})</span>
                                {%  endif %}
                            </td>
                            <td class="nowrap hours">{{ contract.hours_worked|floatformat:2 }} ({% widthratio contract.hours_worked contract.contracted_hours 100 %}%)</td>
                            <td class="nowrap hours">{{ contract.nonbillable_hours_worked|floatformat:2 }}</td>
                            <td class="hidden-phone">
                                <div class="project-bar" style="width: 100%"
                                    data-fraction="{{ contract.fraction_schedule }}"></div>
                                <div class="project-bar" style="width: 100%"
                                    data-fraction="{{ contract.fraction_hours }}"></div>
                            </td>
                            <td class="nowrap">{{ contract.get_type_display }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

        </div>
    </div>
{% endblock content %}